# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe8862012e3fd6cb2bc8ff6e46ad7785530d55078cabfe32bf3e4ae07a90e20c7d319e44b1482b5d584a5a6099888ca460175e5426825cb204895bc2d614732b

test:
  secret_key_base: f71bedee40e5dd1c40d2c0a80cd3bc64ce901c5b9258e4d7ba350d45c709040032df476236a8f44f11b51b0366b9b8c505cb304296233dc31720f94d29be9a55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
